name: Jest Reporter
description: Jest action adding checks and annotations to your pull requests.
branding:
  icon: check
  color: green
inputs:
  github-token:
    description: Github Token
    required: true
  result-file:
    description: jest result file path for json
    required: false
    default: result.json
  action-name:
    description: Display name. Make sure this name is unique within the workflow.
    required: false
    default: Jest Test Results

runs:
  using: node16
  main: dist/index.js
